spring:
  application:
    name: ffvtraceability-auth-server
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:ffvtraceability}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: 300000
      connection-timeout: 20000
    
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      continue-on-error: false
        
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:9000}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# OAuth2 授权服务器配置
auth-server:
  issuer: ${AUTH_SERVER_ISSUER:http://localhost:9000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    # 与令牌相关的配置都通过 data.sql 中的客户端配置来控制，
    # 这样更符合 OAuth2 的最佳实践，因为不同的客户端可能需要不同的令牌配置。


# 安全配置
security:
  jwt:
    key-store: ${JWT_KEYSTORE_PATH:classpath:keys/jwt-signing-keys.jks}
    key-store-password: ${JWT_KEYSTORE_PASSWORD:ffvtraceability}
    key-alias: ${JWT_KEY_ALIAS:jwt-signing-key}
    private-key-passphrase: ${JWT_KEY_PASSWORD:ffvtraceability}

# 日志配置
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.springframework.security.oauth2: ${LOG_LEVEL_OAUTH2:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.dddml.ffvtraceability: ${LOG_LEVEL_APP:INFO}
#   file:
#     name: ${LOG_FILE_PATH:/var/log/ffvtraceability/auth-server.log}
#   pattern:
#     file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
