// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.article;

import org.dddml.ffvtraceability.specialization.*;
import org.springframework.stereotype.Component;


@Component
public class UpdateBodyLogic implements IUpdateBodyLogic {

    public ArticleEvent.ArticleBodyUpdated verify(java.util.function.Supplier<ArticleEvent.ArticleBodyUpdated> eventFactory, ArticleState articleState, String body, VerificationContext verificationContext) {
        ArticleEvent.ArticleBodyUpdated e = eventFactory.get();
        e.setBody(body);
        return e;
    }

    public ArticleState mutate(ArticleState articleState, String body, MutationContext<ArticleState, ArticleState.MutableArticleState> mutationContext) {
        ArticleState.MutableArticleState s = mutationContext.createMutableState(articleState);
        s.setBody(body);
        return s;
    }

}


