server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
    datasource:
      url: jdbc:postgresql://${AUTH_DB_HOST:127.0.0.1}:${AUTH_DB_PORT:5432}/${AUTH_DB_NAME:ffvtraceability}
      username: ${AUTH_DB_USERNAME:postgres}
      password: ${AUTH_DB_PASSWORD:123456}
      driver-class-name: org.postgresql.Driver

  # 业务数据源
  datasource:
    url: jdbc:postgresql://${BUSINESS_DB_HOST:127.0.0.1}:${BUSINESS_DB_PORT:5432}/${BUSINESS_DB_NAME:ffvtraceability_business}
    username: ${BUSINESS_DB_USERNAME:postgres}
    password: ${BUSINESS_DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG
    org.dddml.ffvtraceability: DEBUG

cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,X-Requested-With"
  allow-credentials: true 