// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.shipment;

import java.math.*;
import java.util.*;
import org.dddml.ffvtraceability.domain.*;
import org.dddml.ffvtraceability.specialization.*;
import org.springframework.stereotype.Component;


import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Implementation of the Shipment.ShipmentAction command logic.
 */
@Component("(shipment_ShipmentAction)")
public class ShipmentActionLogic implements IShipmentActionLogic {
    /**
     * Verifies the Shipment.ShipmentAction command by performing validation logic
     * before the state mutation. Creates and returns an event.
     * 
     * @param eventFactory The supplier that creates new ShipmentEvent.ShipmentActionEvent events
     * @param shipmentState The current state of the Shipment aggregate
     * @param value 
     * @param verificationContext The context information for the verification process
     * @return An event that will be applied to the current state to update the Shipment
     */
    public ShipmentEvent.ShipmentActionEvent verify(java.util.function.Supplier<ShipmentEvent.ShipmentActionEvent> eventFactory, ShipmentState shipmentState, String value, VerificationContext verificationContext) {
        ShipmentEvent.ShipmentActionEvent e = eventFactory.get();
        // TODO: implement
        return e;
    }

    /**
     * Performs the state mutation operation of Shipment.ShipmentAction command.
     *
     * @param shipmentState The current immutable state of the Shipment
     * @param value 
     * @param mutationContext The context that provides functionality including creating mutable state
     * @return The new state of the Shipment
     */
    public ShipmentState mutate(ShipmentState shipmentState, String value, MutationContext<ShipmentState, ShipmentState.MutableShipmentState> mutationContext) {
        ShipmentState.MutableShipmentState s = mutationContext.createMutableState(shipmentState);
        AbstractShipmentAggregate.SimpleShipmentShipmentActionCommandHandler cmdHandler = new AbstractShipmentAggregate.SimpleShipmentShipmentActionCommandHandler();
        cmdHandler.execute(new PropertyCommandContext<>() {
            @Override
            public String getContent() {
                return value;
            }

            @Override
            public Supplier<String> getStateGetter() {
                return shipmentState::getStatusId;
            }

            @Override
            public Consumer<String> getStateSetter() {
                return s::setStatusId;
            }

            @Override
            public String getOuterCommandType() {
                return "ShipmentAction";
            }

            @Override
            public Object getExecutionEnvironment() {
                return null;
            }
        });
        return s; // Return the updated state
    }
}
