// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffCustomerProjection {
    String getCustomerId();

    String getCustomerName();

    String getGgn();

    String getGln();

    String getExternalId();

    String getPreferredCurrencyUomId();

    String getDescription();

    String getStatusId();

    String getCustomerShortName();

    String getTaxId();

    String getGs1CompanyPrefix();

    String getInternalId();

    String getTpaNumber();

    String getCustomerTypeEnumId();

    String getCustomerProductTypeDescription();

    String getCertificationCodes();

    String getBankAccountInformation();

    String getTelecomCountryCode();

    String getTelephone();

    String getEmail();

    String getWebSite();

    String getActive();

}

