// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffFacilityLocationProjection {
    String getLocationSeqId();

    String getLocationTypeEnumId();

    String getAreaId();

    String getAisleId();

    String getSectionId();

    String getLevelId();

    String getPositionId();

    String getGeoPointId();

    String getActive();

}

