// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffFacilityProjection {
    String getFacilityId();

    String getFacilityTypeId();

    String getParentFacilityId();

    String getOwnerPartyId();

    String getFacilityName();

    java.math.BigDecimal getFacilitySize();

    String getFacilitySizeUomId();

    String getDescription();

    String getGeoPointId();

    String getGeoId();

    String getActive();

    String getGln();

    String getFfrn();

}

