// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffGeoProjection {
    String getGeoId();

    String getGeoTypeId();

    String getGeoName();

    String getGeoCode();

    String getGeoSecCode();

    String getAbbreviation();

    String getWellKnownText();

    Long getSequenceNumber();

    String getParentGeoId();

}

