// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffInventoryTransferProjection {
    String getInventoryTransferId();

    String getStatusId();

    String getInventoryItemId();

    String getFacilityId();

    String getLocationSeqId();

    String getContainerId();

    String getFacilityIdTo();

    String getLocationSeqIdTo();

    String getContainerIdTo();

    String getItemIssuanceId();

    java.time.Instant getSendDate();
    java.time.Instant getReceiveDate();
    String getComments();

}

