// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffInventoryItemDetailProjection {
    String getInventoryItemId();

    String getInventoryItemDetailSeqId();

    OffsetDateTime getEffectiveDate();

    java.math.BigDecimal getQuantityOnHandDiff();

    String getShipmentId();

    String getReceiptId();

    String getPhysicalInventoryId();

    String getDescription();

    String getInventoryTransferId();

}

