// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffInventoryByLotNoProjection {
    String getProductId();

    String getProductInternalId();

    String getLotId();

    String getLotNo();

    String getFacilityId();

    String getQuantityUomId();

    java.math.BigDecimal getQuantityIncluded();

    String getCaseUomId();

    java.math.BigDecimal getQuantityOnHandTotal();

}

