// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffInventoryItemProjection {
    String getInventoryItemId();

    String getProductId();

    String getProductName();

    String getSupplierId();

    String getSupplierShortName();

    String getFacilityId();

    String getLotId();

    String getLocationSeqId();

    String getComments();

    java.math.BigDecimal getQuantityOnHandTotal();

    OffsetDateTime getCreatedAt();

}

