// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffInventoryVarianceProjection {
    String getPhysicalInventoryId();

    String getInventoryItemId();

    String getVarianceReasonId();

    java.math.BigDecimal getQuantityOnHandVar();

    String getComments();

    java.time.Instant getCreatedAt();
}

