// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffPurchaseOrderItemProjection {
    String getOrderItemSeqId();

    String getExternalId();

    String getProductId();

    String getSupplierProductId();

    java.math.BigDecimal getQuantity();

    java.math.BigDecimal getCancelQuantity();

    java.math.BigDecimal getSelectedAmount();

    java.math.BigDecimal getUnitPrice();

    String getItemDescription();

    String getComments();

    String getStatusId();

    String getSyncStatusId();

    OffsetDateTime getEstimatedShipDate();

    OffsetDateTime getEstimatedDeliveryDate();

}

