// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffProductAssociationProjection {
    String getProductId();

    String getInternalId();

    String getProductName();

    String getProductIdTo();

    String getProductAssocTypeId();

    Long getSequenceNum();

    java.time.Instant getFromDate();
    java.math.BigDecimal getQuantity();

    java.math.BigDecimal getScrapFactor();

    OffsetDateTime getCreateAt();

    String getCreatedBy();

}

