// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffQaInspectionProjection {
    String getQaInspectionId();

    String getReceiptId();

    String getStatusId();

    String getInspectionTypeId();

    String getProductId();

    String getLotId();

    String getSupplierId();

    String getComments();

    String getInspectionFacilityId();

    String getInspectedBy();

    String getCreatedBy();

    java.time.Instant getInspectedAt();
    java.time.Instant getCreatedAt();
    java.time.Instant getUpdatedAt();
}

