// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffReceivingDocumentProjection {
    String getDocumentId();

    String getStatusId();

    String getPartyIdTo();

    String getPartyIdFrom();

    String getPartyNameFrom();

    String getOriginFacilityId();

    String getOriginFacilityName();

    String getDestinationFacilityId();

    String getPrimaryOrderId();

    String getPrimaryReturnId();

    String getPrimaryShipGroupSeqId();

    OffsetDateTime getCreatedAt();

}

