// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffRawItemProjection {
    String getProductId();

    String getProductName();

    String getInternalName();

    String getBrandName();

    String getDescription();

    String getSmallImageUrl();

    String getMediumImageUrl();

    String getLargeImageUrl();

    String getQuantityUomId();

    String getStatusId();

    String getHeightUomId();

    java.math.BigDecimal getProductHeight();

    java.math.BigDecimal getShippingHeight();

    String getWidthUomId();

    java.math.BigDecimal getProductWidth();

    java.math.BigDecimal getShippingWidth();

    String getDepthUomId();

    java.math.BigDecimal getProductDepth();

    java.math.BigDecimal getShippingDepth();

    String getDiameterUomId();

    java.math.BigDecimal getProductDiameter();

    String getActive();

    String getInternalId();

}

