// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffReceivingDocumentProjection {
    String getDocumentId();

    String getStatusId();

    String getPartyIdTo();

    String getPartyIdFrom();

    String getPartyNameFrom();

    String getOriginFacilityId();

    String getOriginFacilityName();

    String getDestinationFacilityId();

    String getPrimaryOrderId();

    String getPrimaryReturnId();

    String getPrimaryShipGroupSeqId();

    String getQaStatusId();

    String getQaInspectionStatusId();

    java.time.Instant getCreatedAt();
    String getOriginFacilityFacilityId();

    String getOriginFacilityFacilityTypeId();

    String getOriginFacilityParentFacilityId();

    String getOriginFacilityOwnerPartyId();

    String getOriginFacilityFacilityName();

    java.math.BigDecimal getOriginFacilityFacilitySize();

    String getOriginFacilityFacilitySizeUomId();

    String getOriginFacilityDescription();

    String getOriginFacilityGeoPointId();

    String getOriginFacilityGeoId();

    String getOriginFacilityActive();

    String getOriginFacilityGln();

    String getOriginFacilityFfrn();

    Long getOriginFacilityFacilityLevel();

    String getOriginFacilityInternalId();

    Long getOriginFacilitySequenceNumber();

    String getDestinationFacilityFacilityId();

    String getDestinationFacilityFacilityTypeId();

    String getDestinationFacilityParentFacilityId();

    String getDestinationFacilityOwnerPartyId();

    String getDestinationFacilityFacilityName();

    java.math.BigDecimal getDestinationFacilityFacilitySize();

    String getDestinationFacilityFacilitySizeUomId();

    String getDestinationFacilityDescription();

    String getDestinationFacilityGeoPointId();

    String getDestinationFacilityGeoId();

    String getDestinationFacilityActive();

    String getDestinationFacilityGln();

    String getDestinationFacilityFfrn();

    Long getDestinationFacilityFacilityLevel();

    String getDestinationFacilityInternalId();

    Long getDestinationFacilitySequenceNumber();

}

