// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffReceivingItemProjection {
    String getReceiptId();

    String getProductId();

    String getProductName();

    String getSmallImageUrl();

    String getQuantityUomId();

    String getCaseUomId();

    String getInternalId();

    String getGtin();

    String getLotId();

    String getLocationSeqId();

    String getLocationName();

    String getItemDescription();

    java.math.BigDecimal getQuantityAccepted();

    java.math.BigDecimal getQuantityRejected();

    Long getCasesAccepted();

    Long getCasesRejected();

    String getOrderId();

    String getOrderItemSeqId();

    String getReturnId();

    String getReturnItemSeqId();

    String getRejectionId();

    String getShipmentId();

    String getShipmentItemSeqId();

    String getShipmentPackageSeqId();

    java.math.BigDecimal getOutstandingOrderQuantity();

    String getQaInspectionStatusId();

    Boolean getDeleted();

}

