// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffRawItemInventoryItemProjection {
    String getLotNo();

    String getReceivingRecord();

    java.time.Instant getReceivedAt();
    String getOrderId();

    String getQaStatusId();

    String getLocationCode();

    java.math.BigDecimal getQuantityOnHandTotal();

    String getQuantityUomId();

    java.math.BigDecimal getQuantityIncluded();

    String getCaseUomId();

}

