// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffSupplierProjection {
    String getSupplierId();

    String getSupplierName();

    String getGgn();

    String getGln();

    String getExternalId();

    String getPreferredCurrencyUomId();

    String getDescription();

    String getStatusId();

}

