// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffShipmentBoxTypeProjection {
    String getShipmentBoxTypeId();

    String getDescription();

    String getDimensionUomId();

    java.math.BigDecimal getBoxLength();

    java.math.BigDecimal getBoxWidth();

    java.math.BigDecimal getBoxHeight();

    String getWeightUomId();

    java.math.BigDecimal getBoxWeight();

    String getActive();

    String getBoxTypeName();

}

