// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffSalesOrderItemProjection {
    String getOrderItemSeqId();

    String getExternalId();

    String getProductId();

    String getCustomerProductId();

    String getProductName();

    String getGtin();

    java.math.BigDecimal getQuantity();

    java.math.BigDecimal getCancelQuantity();

    java.math.BigDecimal getSelectedAmount();

    java.math.BigDecimal getUnitPrice();

    String getItemDescription();

    String getComments();

    String getItemStatusId();

    String getItemSyncStatusId();

    String getItemFulfillmentStatusId();

    java.time.Instant getEstimatedShipDate();
    java.time.Instant getEstimatedDeliveryDate();
}

