// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface BffSupplierRawItemProjection {
    String getProductId();

    String getSupplierId();

    String getSupplierShortName();

    Long getVersion();

    String getCurrencyUomId();

    java.math.BigDecimal getMinimumOrderQuantity();

    java.time.Instant getAvailableFromDate();
    java.time.Instant getAvailableThruDate();
    String getBrandName();

    String getGtin();

    java.math.BigDecimal getQuantityIncluded();

    Long getPiecesIncluded();

    String getSupplierName();

    String getActive();

    String getCaseUomId();

    String getOrganicCertifications();

    String getMaterialCompositionDescription();

    String getCountryOfOrigin();

    String getCertificationCodes();

    Long getIndividualsPerPackage();

    String getProduceVariety();

    String getHsCode();

    String getStorageConditions();

    String getShelfLifeDescription();

    String getHandlingInstructions();

    String getWeightUomId();

    java.math.BigDecimal getShippingWeight();

    java.math.BigDecimal getProductWeight();

}

