// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffUomProjection {
    String getUomId();

    String getUomTypeId();

    String getAbbreviation();

    Long getNumericCode();

    String getDescription();

    String getGs1AI();

    String getActive();

    String getUomName();

}

