// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import org.dddml.ffvtraceability.domain.*;

public interface BffWipInventoryGroupProjection {
    String getProductId();

    String getProductName();

    String getQuantityUomId();

    String getFacilityId();

    String getFacilityName();

    java.math.BigDecimal getQuantityOnHandTotal();

}

