// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.repository;

import java.time.OffsetDateTime;
import org.dddml.ffvtraceability.domain.*;

public interface SupplierProductAssocIdProjection {
    String getProductId();

    String getPartyId();

    String getCurrencyUomId();

    java.math.BigDecimal getMinimumOrderQuantity();

    java.time.Instant getAvailableFromDateInstant();
}

