configuration:
  sequenceNumber: 1000
  metadata:
    NoHibernate5: true
    ShouldUseJakartaEE: true
    #ShouldStaticallyInvokeJavaLogicFunctions: true
    ShouldInvokeJavaDefaultLogicFunctions: true
    JsonUriPathVariableEnabled: true
    SpringSecurityEnabled: true
    JpaProjectionInterfaceSubPackageName: "repository"
    JakartaValidationEnabled: true
    DomainEventPublishingEnabled: true
  multiTenancy:
    discriminatorBasedMultiTenancyEnabled: true

  validationConstraints:
    Gs1Batch:
      message: "Invalid GS1 batch format"
      pattern: "^[A-Z0-9/\\-._]{1,20}$"
  namedStringPatterns:
    FFRN: "^\\d{11}$"
    GGN: "^\\d{13}$"
    GLN: "^\\d{12}\\d$"

  # ---------------------------------------------------------------------------
  # Remove the hard coded exception handling logic
  onRestfulMethodStart:
    Java: ""
  onRestfulMethodEnd:
    Java: ""
  # ---------------------------------------------------------------------------

  hibernate:
    hibernateTypes:
      StringList:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "java.util.ArrayList"
      ObjectList:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "java.util.ArrayList"
      ConsistentEqualityMap:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "org.dddml.ffvtraceability.domain.ConsistentEqualityMap"
  java:
    typeMappings:
      boolean: Boolean
      integer: Integer
      OffsetDateTime: OffsetDateTime
    typePackages:
      OffsetDateTime: java.time

  defaultTimestampType: OffsetDateTime
  defaultReservedPropertyMetadata:
    noDeleted: true
    noActive: true
    deleted:
      name: "__Deleted__" # A placeholder that should not be used.
    active:
      name: "__Active__" # A placeholder that should not be used.

  typeDefinitions:
    StringList:
      sqlType: json
      javaType: java.util.List<String>
    ObjectList:
      sqlType: json
      javaType: java.util.List<Object>
    HashHex:
      sqlType: VARCHAR(64)
      javaType: String
    ConsistentEqualityMap:
      sqlType: json
      javaType: org.dddml.ffvtraceability.domain.ConsistentEqualityMap

    id:
      sqlType: VARCHAR(20)
      cSharpType: string
      javaType: String
    id-ne:
      sqlType: VARCHAR(20)
      cSharpType: string
      javaType: String

    date-time:
      #cSharpType: DateTime?
      sqlType: timestamptz
      javaType: OffsetDateTime

    very-long:
      sqlType: TEXT
      cSharpType: string
      javaType: String

    fixed-point:
      sqlType: DECIMAL(18,6)
      javaType: java.math.BigDecimal
    # The types decimal and numeric are equivalent. Both types are part of the SQL standard.
    # fixed-point:
    #   sqlType: NUMERIC(18,6)
    #   cSharpType: decimal?
    #   javaType: java.math.BigDecimal

    floating-point:
      sqlType: FLOAT8
      javaType: Double

    integer:
      sqlType: INTEGER
      javaType: Integer

    numeric:
      sqlType: DECIMAL(20,0)
      javaType: Long
