configuration:
  sequenceNumber: 1000
  multiTenancy:
    discriminatorBasedMultiTenancyEnabled: false
  hibernate:
    hibernateTypes:
      StringList:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "java.util.ArrayList"
      ObjectList:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "java.util.ArrayList"
      ConsistentEqualityMap:
        mappingType: "io.hypersistence.utils.hibernate.type.json.JsonType"
        parameters:
          "org.hibernate.type.ParameterType": "org.dddml.ffvtraceability.domain.ConsistentEqualityMap"
  java:
    typeMappings:
      "boolean": "Boolean"
      "integer": "Integer"

  defaultReservedPropertyMetadata:
    noActive: true

typeDefinitions:
  StringList:
    sqlType: json
    javaType: java.util.List<String>
  ObjectList:
    sqlType: json
    javaType: java.util.List<Object>
  HexHash:
    sqlType: VARCHAR(64)
    javaType: String
  ConsistentEqualityMap:
    sqlType: json
    javaType: org.dddml.ffvtraceability.domain.ConsistentEqualityMap

  id:
    sqlType: VARCHAR(20)
    cSharpType: string
    javaType: String
  id-ne:
    sqlType: VARCHAR(20)
    cSharpType: string
    javaType: String

