valueObjects:
  Gs1AppIdComponent:
    properties:
      Optional:
        type: boolean
      Type:
        type: string
      FixedLength:
        type: boolean
      Length:
        type: integer
      CheckDigit:
        type: boolean
      Key:
        type: boolean
      Format:
        type: string
      CheckCharacters:
        type: boolean
  Gs1AppIdRange:
    properties:
      Start:
        type: string
      End:
        type: string
      Item:
        type: string

aggregates:
  Gs1ApplicationIdentifier:
    metadata:
      AbsolutelyNoEventSourcing: true
    id:
      name: ApplicationIdentifier
      type: string
    properties:
      FormatString:
        type: string
      Label:
        type: string
      Description:
        type: string
      Fnc1required:
        type: boolean
      Regex:
        type: string
      Note:
        type: string
        length: 500
      Title:
        type: string
      SeparatorRequired:
        type: boolean
      Components:
        itemType: Gs1AppIdComponent
        isList: true
        tableName: gs1_application_identifier_component
        indexColumnName: component_index
      Gs1DigitalLinkPrimaryKey:
        type: boolean
      Gs1DigitalLinkQualifiers:
        type: ObjectList # item of list: StringList
      #TODO:  itemType: StringList
      #  isList: true
      Excludes:
        type: ObjectList # item of list: Gs1AppIdRange or String
      Requires:
        type: ObjectList # item of list: Gs1AppIdRange or StringList or String
      Start:
        type: string
      End:
        type: string
