spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    default-property-inclusion: NON_EMPTY

  messages:
    encoding: UTF-8
    basename: i18n/messages

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    static-path-pattern: /**
    servlet:
      path: /api

  resources:
    static-locations: classpath:/static/
    add-mappings: true

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

server:
  port: 1023
  servlet:
    context-path: /
    register-default-servlet: true

  compression:
    enabled: true
    min-response-size: 20480
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

  max-http-header-size: 81920

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks

# 如果需要自定义CORS配置，可以添加：
cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,X-Requested-With"
  allow-credentials: true
