// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.ffvtraceability.domain.supplierproduct;

import org.dddml.ffvtraceability.specialization.*;


public class DisableLogic {

    public static SupplierProductEvent.SupplierProductDisabled verify(java.util.function.Supplier<SupplierProductEvent.SupplierProductDisabled> eventFactory, SupplierProductState supplierProductState, VerificationContext verificationContext) {
        SupplierProductEvent.SupplierProductDisabled e = eventFactory.get();
        return e;
    }

    public static SupplierProductState mutate(SupplierProductState supplierProductState, MutationContext<SupplierProductState, SupplierProductState.MutableSupplierProductState> mutationContext) {
        SupplierProductState.MutableSupplierProductState s = mutationContext.createMutableState(supplierProductState);
        s.setAvailableThruDate(supplierProductState.getSupplierProductAssocId().getAvailableFromDate());
        return s;
    }

}


