server:
  port: 8080

spring:
  application:
    name: file-service
  
  datasource:
    # url: jdbc:h2:mem:filedb
    # driver-class-name: org.h2.Driver
    # username: sa
    # password: password
    url: jdbc:postgresql://127.0.0.1/test4
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        # hbm2ddl:
        #   auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

  mvc:
    cors:
      # 开发环境临时配置，生产环境应该限制为特定域名
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "*"
      # 可选配置
      # allow-credentials: true
      # max-age: 3600

storage:
  security:
    allow-anonymous-upload: true
  
  type: minio
  
  gcs:
    project-id: woven-justice-441107-h8
    private-bucket: flex-api-private
    public-bucket: flex-api-public

  aws:
    access-key: your-aws-access-key
    secret-key: your-aws-secret-key
    region: your-aws-region
    private-bucket: flex-api-private
    public-bucket: flex-api-public
  
  minio:
    endpoint: http://47.88.28.103:9002
    public-endpoint: http://47.88.28.103:9002
    access-key: 2D9TwWDVmUQPB9TARDmf
    secret-key: nT2X0hxdI5UbnJdo5kSV88jnmGUFEYA4Ddww1Kbf
    bucket: my-bucket
