server:
  port: 8080

spring:
  application:
    name: file-service
  
  datasource:
    url: jdbc:h2:mem:filedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

storage:
  security:
    allow-anonymous-upload: true
  
  type: gcs
  
  gcs:
    project-id: woven-justice-441107-h8
    private-bucket: flex-api-private
    public-bucket: flex-api-public

  aws:
    access-key: your-aws-access-key
    secret-key: your-aws-secret-key
    region: your-aws-region
    private-bucket: flex-api-private
    public-bucket: flex-api-public
  
  minio:
    endpoint: http://localhost:9000
    access-key: sR0M20dawA1y4SRBnz9p
    secret-key: c5pyo789dmbfdI8GDspnRZkbrg8XDwzUVhULCCYS
    bucket: my-bucket