server:
  port: 8082

spring:
  application:
    name: file-service
  
  datasource:
    # url: jdbc:h2:mem:filedb
    # driver-class-name: org.h2.Driver
    # username: sa
    # password: password
    url: jdbc:postgresql://127.0.0.1/test4
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        # hbm2ddl:
        #   auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "*"
      allow-credentials: false
      max-age: 3600

storage:
  security:
    allow-anonymous-upload: true
  
  type: minio
  
  gcs:
    project-id: woven-justice-441107-h8
    private-bucket: flex-api-private
    public-bucket: flex-api-public

  aws:
    access-key: your-aws-access-key
    secret-key: your-aws-secret-key
    region: your-aws-region
    private-bucket: flex-api-private
    public-bucket: flex-api-public
  
  cos:
    secret-id: YOUR_SECRET_ID
    secret-key: YOUR_SECRET_KEY
    region: ap-nanjing
    private-bucket: ffvt-private
    public-bucket: ruichaungqi-skin-1252161476
    public-endpoint: https://ruichaungqi-skin-1252161476.cos.ap-nanjing.myqcloud.com
  
  minio:
    endpoint: http://fp.ablueforce.com:9002  #minio服务的地址（端口为参数 --address的值，默认为9000），我们在启动docker的时候将其映射为宿主的 9002 端口 (-p 9002:9000)
    public-endpoint: https://fp.ablueforce.com #上传文件之后返回的url的前缀
    #因为我们自己启动的 minio docker实例没有配置 https，真正的 https 是来自于nginx的配置
    #拿文件https://fp.ablueforce.com/my-bucket/public/5c813eae-8ecc-4d1a-b8c8-fed5f93781ca.jpg 来说，
    #在nginx中，会将这个地址会被反向代理到minio的地址
    #http://localhost:9002/my-bucket/public/5c813eae-8ecc-4d1a-b8c8-fed5f93781ca.jpg 上
    access-key: ZMBht5YRzMpTI2PmYNxD
    secret-key: ksZSdng7eFNoHgHsR46PXoz2HpkmEwDd64HuuuKk
    bucket: my-bucket
