spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/test4
    username: postgres
    password: 123456
#    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
#    username: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        hbm2ddl:
          auto: update
        connection:
          pool_size: 2
        cache:
          provider_class: "org.hibernate.cache.EhCacheProvider"
          use_second_level_cache: false

