spring:
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
#    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
#    username: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
